name: loco_instant_flutter
description: Skeleton Flutter app for Loco Instant
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.6
  supabase_flutter: ^2.5.8
  google_maps_flutter: ^2.6.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/